name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## What's Changed
  $CHANGES

  **Contributors**:
  $CONTRIBUTORS
