name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Bazel output
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
            bazel-out
          key: ${{ runner.os }}-bazel-${{ hashFiles('**/WORKSPACE', '**/BUILD.bazel', '**/BUILD', '**/.bazelrc', '**/.bazelversion') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Run Gazelle
        run: bazel run //:gazelle

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //...
