name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run Gazelle
        run: bazel run //:gazelle
        
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v2
      # add gazelle

      - run: bazel build //...
      - run: bazel test //...
      
    
