name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Run Gazelle
        run: bazel run //:gazelle
      - name: Build
        run: bazel build //... --verbose_failures --sandbox_debug
      - name: Test
        run: bazel test //... --verbose_failures --sandbox_debug
