name: Release Drafter

on:
  push:
    branches:
      - main  # or 'master' depending on your default branch

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: 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
